# -*- coding: utf-8 -*-
#
# ZurmoCRM Documentation documentation build configuration file, created by
# sphinx-quickstart on Fri Apr  4 11:56:07 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# Append the top level directory of the docs, so we can import from the config dir.
sys.path.insert(0, os.path.abspath('..'))

# Pull in all the configuration options defined in the global config file..
from config.base import *

language = 'en'